In [142]:
# importing important libraries

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV,RandomizedSearchCV
import warnings
warnings.filterwarnings('ignore')

from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

Sub parts in data projects

1 data loading

2 data processing and eda

3 feature enginerring

4 train test split

5 model selection

6 evaluvation

In [143]:
# data loading

df2 = pd.read_csv('F:\ML Projects\Machine Learning Projects\DataFiles\Diabeties.csv')

df2.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [144]:
# now eda and feature enginering

# checking for any missing values present in the data

df2.isnull().sum()

# from the below we dont have any missing values present in the dataset

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [145]:
df2.isna().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [146]:
# checking for any duplicate values

df2.duplicated().sum()

# There are no duplicate values present in the dataset

0

In [147]:
# now we will go through summary statistics

df2.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [148]:
# for the above glucose, bp, skin thickness, insulin, BMI, for those we need to conisder the min values 

# glucose - 70 mg/dL

# bp - 90 mmHg (systolic) over 60 mmHg (diastolic)

# skin thickness - 1 to 5 mm

# insulin - 2 to 25 µIU/mL

# BMI - 18.5

In [149]:
df2.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [150]:
df2.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [151]:
df2.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [152]:
df2['Glucose'] = df2['Glucose'].replace(0,df2['Glucose'].median())
df2['BloodPressure'] = df2['BloodPressure'].replace(0,df2['BloodPressure'].median())
df2['SkinThickness'] = df2['SkinThickness'].replace(0,df2['SkinThickness'].median())
df2['Insulin'] = df2['Insulin'].replace(0,df2['Insulin'].median())
df2['BMI'] = df2['BMI'].replace(0,df2['BMI'].median())

In [153]:
df2.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,30.5,33.6,0.627,50,1
1,1,85,66,29,30.5,26.6,0.351,31,0
2,8,183,64,23,30.5,23.3,0.672,32,1
3,1,89,66,23,94.0,28.1,0.167,21,0
4,0,137,40,35,168.0,43.1,2.288,33,1

In [154]:
df2.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,121.656250,72.386719,27.334635,94.652344,32.450911,0.471876,33.240885,0.348958
std,3.369578,30.438286,12.096642,9.229014,105.547598,6.875366,0.331329,11.760232,0.476951
min,0.000000,44.000000,24.000000,7.000000,14.000000,18.200000,0.078000,21.000000,0.000000
25%,1.000000,99.750000,64.000000,23.000000,30.500000,27.500000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,31.250000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [155]:
# dividing the data into independent and dependent varaibles

X = df2.drop('Outcome',axis=1)
y = df2['Outcome']

In [156]:
X.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,30.5,33.6,0.627,50
1,1,85,66,29,30.5,26.6,0.351,31
2,8,183,64,23,30.5,23.3,0.672,32
3,1,89,66,23,94.0,28.1,0.167,21
4,0,137,40,35,168.0,43.1,2.288,33

In [157]:
y.head()

0    1
1    0
2    1
3    0
4    1
Name: Outcome, dtype: int64

In [158]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [159]:
scalar = StandardScaler()

In [160]:
X_train = scalar.fit_transform(X_train)
X_test = scalar.transform(X_test)

In [161]:
models = {'Lr':LogisticRegression(),
          'SVC':SVC(),
          'DT':DecisionTreeClassifier(),
          'Rf':RandomForestClassifier()
          }

In [162]:
def evaluvate_model(y_true, y_pred):
    y_true = np.array(y_true)
    y_pred = np.array(y_pred)

    matrix = confusion_matrix(y_true, y_pred)
    report = classification_report(y_true, y_pred)
    acc = accuracy_score(y_true, y_pred)

    return matrix, report, acc

In [163]:
model_list = []
acc_score2 = []

for i in range(len(list(models))):
    model=list(models.values())[i]
    model.fit(X_train,y_train)

    #Make Predictions
    y_pred=model.predict(X_test)

    matrix, report, acc =evaluvate_model(y_test.values,y_pred)

    print(list(models.keys())[i])
    model_list.append(list(models.keys())[i])

    print('Model Training Performance')
    print("matrix:",matrix)
    print("report:",report)
    print("acc_score",acc)

    acc_score2.append(acc)
    
    print('='*35)
    print('\n')

Lr
Model Training Performance
matrix: [[140  28]
 [ 35  51]]
report:               precision    recall  f1-score   support

           0       0.80      0.83      0.82       168
           1       0.65      0.59      0.62        86

    accuracy                           0.75       254
   macro avg       0.72      0.71      0.72       254
weighted avg       0.75      0.75      0.75       254

acc_score 0.7519685039370079
===================================


SVC
Model Training Performance
matrix: [[139  29]
 [ 36  50]]
report:               precision    recall  f1-score   support

           0       0.79      0.83      0.81       168
           1       0.63      0.58      0.61        86

    accuracy                           0.74       254
   macro avg       0.71      0.70      0.71       254
weighted avg       0.74      0.74      0.74       254

acc_score 0.7440944881889764
===================================


DT
Model Training Performance
matrix: [[122  46]
 [ 30  56]]
report:               precision    recall  f1-score   support

           0       0.80      0.73      0.76       168
           1       0.55      0.65      0.60        86

    accuracy                           0.70       254
   macro avg       0.68      0.69      0.68       254
weighted avg       0.72      0.70      0.71       254

acc_score 0.7007874015748031
===================================


Rf
Model Training Performance
matrix: [[136  32]
 [ 33  53]]
report:               precision    recall  f1-score   support

           0       0.80      0.81      0.81       168
           1       0.62      0.62      0.62        86

    accuracy                           0.74       254
   macro avg       0.71      0.71      0.71       254
weighted avg       0.74      0.74      0.74       254

acc_score 0.7440944881889764
===================================

In [164]:
models = {
    "LogisticRegression": {
        "model": LogisticRegression(max_iter=1000),
        "params": {
            "C": [0.01, 0.1, 1, 10],
            "penalty": ["l2"],
            "solver": ["lbfgs"]
        }
    },

    "RandomForest": {
        "model": RandomForestClassifier(),
        "params": {
            "n_estimators": [100, 200, 300],
            "max_depth": [None, 5, 10, 20],
            "min_samples_split": [2, 5, 10]
        }
    },

    "SVM": {
        "model": SVC(),
        "params": {
            "C": [0.1, 1, 10],
            "kernel": ["linear", "rbf"],
            "gamma": ["scale", "auto"]
        }
    }
}

In [172]:
best_models = {}

for model_name, model_info in models.items():
    print(f"Running RandomizedSearchCV for {model_name}")

    rscv = RandomizedSearchCV(
        estimator=model_info["model"],
        param_distributions=model_info["params"],
        n_iter=10,
        cv=5,
        scoring="accuracy",
        random_state=42,
        n_jobs=-1
    )

    rscv.fit(X_train, y_train)

    best_models[model_name] = {
        "best_score": rscv.best_score_,
        "best_params": rscv.best_params_,
        "best_estimator": rscv.best_estimator_
    }

    print("Best Score:", rscv.best_score_)
    print("Best Params:", rscv.best_params_)
    print("best_estimator:", rscv.best_estimator_)
    print("-" * 40)

Running RandomizedSearchCV for LogisticRegression
Best Score: 0.7762421473443746
Best Params: {'solver': 'lbfgs', 'penalty': 'l2', 'C': 0.1}
best_estimator: LogisticRegression(C=0.1, max_iter=1000)
----------------------------------------
Running RandomizedSearchCV for RandomForest
Best Score: 0.7762802208261945
Best Params: {'n_estimators': 300, 'min_samples_split': 10, 'max_depth': 10}
best_estimator: RandomForestClassifier(max_depth=10, min_samples_split=10, n_estimators=300)
----------------------------------------
Running RandomizedSearchCV for SVM
Best Score: 0.7684751570531125
Best Params: {'kernel': 'linear', 'gamma': 'scale', 'C': 0.1}
best_estimator: SVC(C=0.1, kernel='linear')
----------------------------------------

In [166]:
best_rf = best_models["RandomForest"]["best_estimator"]

In [167]:
best_rf

RandomForestClassifier(max_depth=10, min_samples_split=5)

In [168]:
models.items()

dict_items([('LogisticRegression', {'model': LogisticRegression(max_iter=1000), 'params': {'C': [0.01, 0.1, 1, 10], 'penalty': ['l2'], 'solver': ['lbfgs']}}), ('RandomForest', {'model': RandomForestClassifier(), 'params': {'n_estimators': [100, 200, 300], 'max_depth': [None, 5, 10, 20], 'min_samples_split': [2, 5, 10]}}), ('SVM', {'model': SVC(), 'params': {'C': [0.1, 1, 10], 'kernel': ['linear', 'rbf'], 'gamma': ['scale', 'auto']}})])